version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pools
    volumes:
      - polls_pg_data:/bitnami/postgresql
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=docker
      - DB_PASSWORD=docker
      - DB_DATABASE=pools
    depends_on:
      - postgres
    networks:
      - app_network

networks:
  app_network:

volumes:
  polls_pg_data:
